name: myGoCI

on:
  push:
    branches: [ "*" ]  # 所有分支发生push事件时都会触发该工作流
  pull_request:
    branches: [ "master" ]  # 当PR的目标分支是master时才会触发该工作流

jobs:

  build_and_push_image:  # job id
    runs-on: ubuntu-latest  # 运行时所需要的虚拟机环境
    steps:
    
    - name: Set up Go 1.23
      uses: actions/setup-go@v4  # 引用别人已经创建好的actions脚本，用来设置go的运行环境
      with:  # 指定actions脚本所需的输入参数，每个都是键值对格式
        go-version: '1.23'
        
    - uses: actions/checkout@v4
    
    - name: Build
      run: go build -v ./...
      
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ""
        
      
